### ISSUE TITLE
Wrong type for "bo"

### ISSUE THREAD

**Issue by vbauwens** [Jorgen-VikingGod/FastLED-GFX#4]
https://github.com/Jorgen-VikingGod/FastLED-GFX/blob/af798fc1ddb1718dc9f30ba713d9a1b8bf190799/FastLED_GFX.cpp#L531

Hello,
I think the type for bo should be uint16_t not CRGB:
uint16_t bo = pgm_read_word(&glyph->bitmapOffset);
Thanks,
Valentin.

**Comment by Jorgen-VikingGod** [comment]
thx for reporting.
Was a search-replace issue.
