### ISSUE TITLE
Canvas is not created / doesn't work

### ISSUE THREAD

**Issue by marcouderzo** [Jorgen-VikingGod/FastLED-GFX#6]
Hi, 
i am using a WS2812B led strip as a Matrix. I setted up everything, but the leds do not turn on as they should. Any advice?

**Comment by Jorgen-VikingGod** [comment]
Did a simple FastLED example works?
Please try to control your strip without using this library first.
If it is working, than please post some code inside here - so I can try to help you

**Comment by marcouderzo** [comment]
Yes, it did. Actually, even the most complex sketches I've written work with FastLED alone.
I tried to get a fresh copy of your library, but nothing changed

This is the code. I edited out most of the loop and replaced it with `canvas.fillScreen(CRGB::Red);`, but still it doesn't work. Looks like the strip is not recieving any data.  Could it be that `canvas.getBuffer()` is not returning to `FastLED.addLeds()` the CRGB LED Array?

```
#include <FastLED.h>
#include <FastLED_GFX.h>
#include <gfxfont.h>
#include <fix_fft.h>   //to get input from audio source, connect audio output to Analog 5.

#define NUM_LEDS 300
#define DATA_PIN 12
#define audioPin A5; // Left or right channel audio positive lead connects here
#define maxExpectedAudio 120   // Change this value to adjust the sensitivity

char data[20];  // FFT array variables
char im[20]={};

GFXcanvas canvas(20,15);

void setup() 
{
  FastLED.addLeds<WS2812B, DATA_PIN, RGB>(canvas.getBuffer(), NUM_LEDS);
  FastLED.setBrightness(70);
  //Serial.begin(9600); //debugging and testing

}

void loop() 
{ 
    canvas.fillScreen(CRGB::Red);
    FastLED.show();
}
```

Am I missing something? 

Also, is FastLED_GFX the best choice to draw lines onto the matrix? What's the difference between this and your LEDMatrix repository, other than the fact that LEDMatrix lets you select the matrix layout?

**Comment by Jorgen-VikingGod** [comment]
I would recommend  the LEDMatrix library I created, it is more stable and has similar functionality.
The FastLED_GFX lib was a first try, but become obsolete after I created the LEDMatrix port.
There you also have a `DrawLine` method.

Btw. your code looks correct - wonder why it did not work. But to be correct - I didn't use it a really long time.

Please give the LEDMatrix lib a try - this should work out of the box and has also more contribution from the community.

**Comment by marcouderzo** [comment]
Thank you very much, I will give LEDMatrix a try for sure!

**Comment by Jorgen-VikingGod** [comment]
thx!
Hopefully I have some time on weekend to reactivate this lib. Really don't know, why it did not work...
